acknowledgements.enabled = true
data_dir = "/var/lib/vector"
timezone = "Europe/Moscow"


[api]
  enabled = true
  address = "0.0.0.0:8686"


[sources.extlogs]
  type = "socket"
  address = "0.0.0.0:41514"
  mode = "udp"
  decoding.codec = "bytes"

[transforms.modify]
  type = "remap"
  inputs = ["extlogs"]
  timezone = "local"
  file = "/etc/vector/vrl/roslogs.vrl"


[sources.vector_metrics]
  type = "internal_metrics"

[sinks.victoriametrics]
  type = "prometheus_remote_write"
  endpoint = "http://127.0.0.1:8428/api/v1/write"
  inputs = ["vector_metrics"]
  healthcheck.enabled = false
  acknowledgements.enabled = false

#[sinks.out]
#  type = "console"
#  inputs = [ "modify" ]
#  encoding.codec = "json"


[sinks.ch-ros]
type = "clickhouse"
inputs = [ "modify" ]
endpoint = "http://127.0.0.1:8123"
database = "logs"
table = "ros_logs"
skip_unknown_fields = true
encoding.timestamp_format = "unix"
buffer.type = "disk"
buffer.max_size = 268435488
buffer.when_full = "block"
acknowledgements.enabled = false
